apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jej9ky9eb-go 
  janus-idp.io/tekton: jej9ky9eb-go
  backstage.io/kubernetes-id: jej9ky9eb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jej9ky9eb-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml