apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jej9ky9eb-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jej9ky9eb-go 
  name: jej9ky9eb-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jej9ky9eb-go 
